### ISSUE TITLE
0.30.0: quoted .env rendering breaks Docker Swarm deployments (`docker stack deploy` does not strip quotes)

### ISSUE THREAD

**Issue by shintaii** [Dokploy/dokploy#5113]
### To Reproduce

# Draft GitHub issue for Dokploy/dokploy — file after review

**Title:** 0.30.0: quoted .env rendering breaks Docker Swarm deployments (`docker stack deploy` does not strip quotes) — full production outage

---

## Describe the bug

Since v0.30.0, `prepareEnvironmentVariablesForFile()` (introduced in #4962 to fix #4694) writes every value in the rendered `.env` wrapped in double quotes, with `\`, `"` and `$` escaped:

```dotenv
DJANGO_SETTINGS_MODULE="config.settings.production"
GOOGLE_CLIENT_CONFIG="{\"web\":{\"client_id\":\"194...\"}}"
```

For `docker compose` this is fine — its dotenv parser unquotes and unescapes. But **Compose projects deployed to Docker Swarm go through `docker stack deploy`, and the Docker CLI's `env_file` parser (`opts.ParseEnvFile`) takes each line verbatim — no quote stripping, no unescaping.** Every container in the stack receives values with literal quotes:

```
DJANGO_SETTINGS_MODULE = "config.settings.production"   (2 literal quote chars included)
```

## Impact

On our production Swarm (Dokploy Cloud, so we cannot pin or downgrade the version), the first deploy after the 0.30.0 rollout poisoned the env of every service in the stack. All Celery/Django services crash-looped on startup:

```
ModuleNotFoundError: No module named '"config'
AttributeError: module 'signal' has no attribute '"SIGQUIT"'. Did you mean: 'SIGQUIT'?
```

Because Swarm keeps previous tasks alive under `start-first`, the failure surfaced gradually as old tasks cycled out — a slow-motion full outage (~13.5 hours degraded, order sync and repricing down). Recovery required manually stripping the quotes from the rendered `.env` on the manager node and running `docker stack deploy` by hand. Any deploy from the Dokploy UI re-poisons the file.

## To Reproduce

1. Compose service on a **Swarm** server (deployed via `docker stack deploy`) with `env_file: .env` and any env var set in the Dokploy environment tab, e.g. `FOO=bar`.
2. Deploy with Dokploy >= 0.30.0.
3. Rendered `.env` contains `FOO="bar"`; inside the container `echo "$FOO"` prints `"bar"` **including the quote characters**.

On 0.29.x the rendered file contained `FOO=bar` and the container received `bar`.

## Expected behavior

Values arrive in containers exactly as entered in the UI, regardless of compose vs Swarm deployment. Options:

- When the target is Swarm/`docker stack deploy`, write plain (pre-0.30.0) values, applying the new quoting only where a dotenv parser will actually consume the file; or
- Never rely on `env_file` quote semantics: resolve variables Dokploy-side and inject them via the stack spec instead of a quoted file.

Please also add a regression test that round-trips env values through an actual `docker stack deploy` on Swarm, not only through compose/dotenv parsers — that is the gap that let #4962 ship.

## Environment

- Dokploy Cloud (version not user-controllable; behavior matches 0.30.0 / PR #4962)
- Docker Swarm multi-node cluster, compose-type application, `env_file: .env`
- Incident date: 2026-08-17/18

## Workaround we use meanwhile

An exec-wrapper in our image entrypoint strips exactly this quoting from `os.environ` before the app starts (no-op for unquoted values), so deploys survive both broken and fixed rendering.

### Current vs. Expected behavior

PRODUCTION DOWN

### Provide environment information

```bash
Dokploy CLOUD
```

### Which area(s) are affected? (Select all that apply)

Docker

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

No
